### ISSUE TITLE
Explorer layout

### ISSUE THREAD

**Issue by MortenHofft** [VtEcostudies/VAL_GBIF_Wordpress#1] opened 2022-09-05 07:46 UTC
On https://val.vtecostudies.org/gbif-explorer/
When clicking the "number of records" button the user is redirected to the hosted portal. 

I assume the hosted portal should be deleted again, since we are now using the embedded library option.

There is also something a bit confusing about the somewhat repeated hero banner
on https://val.vtecostudies.org/ and https://val.vtecostudies.org/gbif-explorer/

Would it perhaps make sense to just stick with the hero banner on https://val.vtecostudies.org/ (possible with some of the metrics from https://val.vtecostudies.org/gbif-explorer/ though I personally prefer the simpler one)

And then link to a data explorer that was more full page? I *think* that would make it a more focused useful tool. Similar to below example:
<img width="1215" alt="Screenshot 2022-09-05 at 09 41 51" src="https://user-images.githubusercontent.com/6759267/188395355-f11bca48-a649-4c6c-8ddf-55c0c94e7c20.png">

**Comment by jloomisVCE** [comment] 2022-09-06 04:27
Sorry, yes the different banners on our Home page and /gbif-explorer/ are a bit confusing. Some of this is leftover behavior from our ALA implementation. We had a brief design discussion and chose these 2 separate views. I agree we need to make the data explorer more like your example.

(However these design decisions are not mine to make! I need to include the VAL team.)

Also: clicking the Banner's top-level links (like # of records) is handled by a [generic javascript listener](https://github.com/VtEcostudies/VAL_GBIF_Wordpress/blob/0bcc8842bafedda94a31af186e590a535d4465fc/gbif_data_explorer.js#L370) used by several different html implementations (eg. our previous hp-vtatlasoflife page in an iframe). I wanted to preserve those here during our development phase for comparison. Also: I want to invoke the data-widget with new parameters, and I haven't figured out how to do that without opening a new page.

**Comment by MortenHofft** [comment] 2022-09-06 07:40
https://github.com/VtEcostudies/VAL_GBIF_Wordpress/blob/0bcc8842bafedda94a31af186e590a535d4465fc/gbif_data_explorer.js#L375

says to open in `_blank` meaning new tab/window.

You could consider just making those links into proper `a-tag` links. Since that is what they are. Instead of styled buttons with Javascript doing the linking. but that would require porting the styling from the buttons - and it might serve other purposes as well. But at first glance I would think that made sense. 

btw`<div id="gbif_react" class="whatever">` class `whatever` was just an example in case you needed to style it.

**Comment by jloomisVCE** [comment] 2022-09-06 16:45
[It's actually hitting this line of code](https://github.com/VtEcostudies/VAL_GBIF_Wordpress/blob/26e5ad411abeb71b1e997ccf189e0827b94f8434/gbif_data_explorer.js#L339). The problem is fixed by calling window.location.assign(url) instead of window.open(url). I don't understand why, without target="_blank" in the former case, another tab was opened.

I removed the various links and one heading and just left the text box because that will be needed to lookup lists of taxa by scientificName and commonName.

**Closed as completed by jloomisVCE** 2022-09-06 16:45 UTC
